config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "runs#index"
  resources :runs do
    resources :comments, only: :create
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :run

  validates :text, presence:true
end

app/models/run.rb
class Run < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :content
    validates :image
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         with_options presence: true do
          validates :nickname
          validates :profile
         end
         PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
         validates_format_of :password, with: PASSWORD_REGEX, message: 'Include both letters and numbers'
  has_many :runs
  has_many :comments
  has_many :likes
  has_many :like_runs, through: :likes, source: :run
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname, :profile])
    devise_parameter_sanitizer.permit(:account_update, keys:[:nickname, :profile])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @run = Run.find(params[:run_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to run_path(@run.id)
    else
      @run = @comment.run
      @comments = @run.comments
      render 'runs/show'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, run_id: params[:run_id])
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
  before_action :set_params, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @runs = Run.includes(:user).order("created_at DESC")
  end

  def new
    @run = Run.new
  end

  def create
    @run = Run.new(run_params)
    if @run.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @run.comments.includes(:user).order("created_at DESC")
  end

  def edit
  end

  def update
    if @run.update(run_params)
      redirect_to run_path(@run.id)
    else
      render :edit
    end
  end

  def destroy
    if @run.destroy
      redirect_to root_path
    end
  end

  private
  def run_params
    params.require(:run).permit(:title, :content, :image).merge(user_id: current_user.id)
  end

  def set_params
    @run = Run.find(params[:id])
  end

  def move_to_index
    if current_user.id != @run.user_id
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_params, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:edit, :upadate]
  before_action :move_to_index, only: [:edit, :update]

  def show
    @runs = @user.runs
  end

  def edit
  end

  def update
    if @user.update(user_params)
      bypass_sign_in(@user)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:nickname, :profile, :email, :password, :password_confirmation)
  end

  def set_params
    @user = User.find(params[:id])
  end

  def move_to_index
    if current_user.id != @user.id
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RunJoy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag('logo.png', class: :logo__btn), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
               <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
               <%= link_to "ユーザー編集", edit_user_path(current_user.id), class: :nav__btn %>
               <%= link_to "新規投稿", new_run_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © RUN JOY All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/runs/_form.html.erb
<%= form_with(model: @run, local: true) do |f|%>
<%= render 'layouts/error_messages', model: f.object %>
  <div class="field">
    <%= f.label :title, "投稿タイトル" %><br />
    <%= f.text_field :title, id:"run_title" %>
  </div>

  <div class="field">
    <%= f.label :content, "投稿内容" %><br />
    <%= f.text_area :content, class: :form__text, id:"run_content" %>
  </div>

  <div class="field">
    <%= f.label :image, "共有したい画像" %><br />
    <%= f.file_field :image, id:"run_image" %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn  %>
  </div>
<% end %>

app/views/runs/_run.html.erb
<div class="card">
  <%= link_to image_tag(run.image, class: :card__img), run_path(run.id) %>
  <div class="card__body">
    <%= link_to run.title, run_path(run.id), class: :card__title%>
    <%= link_to "by #{run.user.nickname}", user_path(run.user.id), class: :card__user %>
  </div>
</div>

app/views/runs/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿内容の編集</h2>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/runs/index.html.erb
<main class="main">
  <div class="inner">
     <% if user_signed_in? %>
       <div class="greeting">
         <%= "こんにちは、" %>
         <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: :greeting__link%>
       </div>
     <% end %>
    <div class="card__wrapper">
      <%= render partial: 'run', collection: @runs %>
    </div>
  </div>
</main>

app/views/runs/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿フォーム</h2>
        <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/runs/show.html.erb
<main class="main">
  <div class="inner">
    <div class="run__wrapper">
      <p class="run__hedding">
        <%= @run.title %>
      </p>
      <%= link_to "by #{@run.user.nickname}", user_path(@run.user.id), class: :run__user %>
      <% if user_signed_in? && current_user.id == @run.user.id %>
        <div class="run__manage">
          <%= link_to "編集する", edit_run_path(@run.id), class: :run__btn %>
          <%= link_to "削除する", run_path(@run.id), method: :delete, class: :run__btn %>
        </div>
      <% end %>
      <div class="run__image">
        <%= image_tag @run.image, class: :joy__image %>
      </div>
      <div class="run__body">
        <div class="run__detail">
          <p class="detail__title">投稿内容</p>
          <p class="detail__message">
            <%= simple_format(h(@run.content)) %>
          </p>
        </div>
      </div>
      <div class="run__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@run, @comment],local: true) do |f|%>
          <%= render 'layouts/error_messages', model: f.object %>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
               <%= comment.text %>
               <%= link_to "#{comment.user.nickname}", user_path(comment.user.id), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ユーザー情報の編集</h2>
        <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="field">
          <%= f.label :email, "メールアドレス" %><br />
          <%= f.email_field :email, id:"user_email", autofocus: true, autocomplete: "email" %>
        </div>

        <div class="field">
          <%= f.label :password, "パスワード（6文字以上の半角英数字のみ）" %><br />
          <%= f.password_field :password, id:"user_password", autocomplete: "new-password" %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, "パスワード再入力" %><br />
          <%= f.password_field :password_confirmation, id:"user_password_confirmation", autocomplete: "new-password" %>
        </div>

        <div class="field">
          <%= f.label :nickname, "ユーザー名" %><br />
          <%= f.text_field :nickname, id:"user_name" %>
        </div>

        <div class="field">
          <%= f.label :profile, "プロフィール" %><br />
          <%= f.text_area :profile, class: :form__text, id:"user_profile" %>
        </div>

        <div class="actions">
          <%= f.submit "新規登録", class: :form__btn  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= @user.nickname %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= simple_format(h(@user.profile)) %></td>
          </tr>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿" %>
      </h2>
      <div class="user__card">
        <%= render partial: 'runs/run', collection: @runs %>
      </div>
    </div>
  </div>
</div>